# Generated by Django 3.1.4 on 2021-03-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
    ]
